### ISSUE TITLE
[Bug]: no effect for Potion effect Instant Damage

### ISSUE THREAD

**Issue by kdg1231** [promcteam/divinity#212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

doesn't effect for instant_damage.
but it works on command.
no effect for only using Instant_damage potions
I can't custom Instant_potion effect. because they doesn't have a Instant_damage effect lines.

### Environment

```markdown
- Server Software:
- ProRPGItems Version:
- ProMCCore Version:
- Plugins:
```

**Comment by Travja** [comment]
I don't think ProRPGItems is even set up to handle potions
