### ISSUE TITLE
Can you get it to support the mmocore

### ISSUE THREAD

**Issue by absedd** [promcteam/divinity#215]
I want to apply the skills of mythicmobs to my server  
I need a plugin that supports both mythicmobs' skill and level systems
mmocore is a great choice, but I'm fed up with his affiliate plugin mmoitem
Can you support the main level of the mmocore

**Comment by goflishMC** [comment]
We fully support proskillapi and prorpgitems. With those 2 plugins you don't need mmocore and we also support skills from proskillapi to work with mythicmobs.
